timezone: Asia/Ho_Chi_Minh
locale: vi-VN

app.port: ${AUTH_SERVER_HTTP_PORT:7070}
account-service-uri: ${ACCOUNT_SERVICE_HOST:http://localhost}:${ACCOUNT_SERVICE_HTTP_PORT:8003}/account
auth-server-uri: ${AUTH_SERVER_HOST:http://localhost}:${AUTH_SERVER_HTTP_PORT:7070}/auth

check-user-scopes: true

firebase:
  db-url: ${FIREBASE_DB_URL:https://arch18-216209.firebaseio.com}
  project-name: ${FIREBASE_PRJ:arch18}
  web-api-key: ${FIREBASE_API_KEY:AIzaSyCIbdNKS3TYkka4cbbm8alNF_cWYo60q2E}
  service-account:
    credential:
      file: file:${FIREBASE_CREDENTIAL_FILE:docker/arch18-216209-firebase-adminsdk-vojrg-dac60a9de8.json}

info:
  id: ${spring.application.name}

logging:
  level:
    com.a18: debug
    root: info

server:
  port: ${AUTH_SERVER_HTTPS_PORT:8470}
  servlet:
    context-path: /auth
  ssl:
    enabled: true
    key-store: ${KEYSTORE:docker/tls/work/keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-store-provider: SUN
    key-alias: ${SSL_KEY_ALIAS:752baa49297f109818d6e06d1b30cfc3c08014c9}
    key-password: ${SSL_KEY_PASSWORD:changeit}
  compression:
    enabled: true
    mime-types: application/hal+json,application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  error:
    whitelabel:
      enabled: false

security:
  oauth2:
    client:
      access-token-validity-seconds: 86400
      authentication-scheme: header
      auto-approve-scopes: true
      client-id: ${OATH2_CLIENT_ID:trusted-client}
      client-secret: ${OATH2_CLIENT_SECRET:changeit}
      grant-type: password
      refresh-token-validity-seconds: 86400
      token-name: token
      access-token-uri: ${auth-server-uri}/oauth/token
      resource-ids:
        https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit
      scope:
        https://www.googleapis.com/auth/identitytoolkit
    resource:
      token-info-uri: ${auth-server-uri}/oauth/check_token
      token-type: bearer

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: auth-server
  config:
    name: ${spring.application.name}
  cloud:
    vault:
      enabled: false
  datasource:
    password: ${POSTGRES_PASSWORD:changeit}
    username: ${POSTGRES_USER:postgres}
    platform: 'postgres'
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:staging-3bwins}?currentSchema=auth&stringtype=unspecified&preferQueryMode=simple
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  output:
    ansi:
      enabled: always
